os:
- linux
python:
- 3.6.5
install:
- pip install -r requirements.txt
- pip install pylint
script:
- pylint --errors-only oktaawscli
deploy:
  provider: pypi
  username: __token__
  password:
    secure: JRNOT52NwrfwKL78n+imILP4yacjPWgF6S6YDPRaReInkIapbfTyibm7+iyn+E98PXBcPGTaUrobsAASB/hzZVX6hM2eg/g0zx1NWM04QPDGh2yYxioJRudi5XNFIVUuJfvcFOGV+UrwlEuISplP6cAb/cvT+WBbWaEur3SUxeuKzVbfixsGTHjCi3v1pmZAt/Hz6VmP2SgVx1spDg4NAU3axbx1e+WG0n8FByJzyLKA6St1uVzOjcSLQiJq4XW1hC+mu6DY7uU0hphv1SdZsLUJHWWAU/l8k/8uaOH+zrEY3m7XpyrKjA0pxHRHC3Hf4RUhOhYbD3puYPzEOC9a6W5LNfMa3zrxY1IKFiWZ+TYPQ6Bg/Mezc21xfUgtYKWzIN3vD+0pObx8Cun8aRKCk7/paBF5UkPrvZGg0cdxqKKb11wAGEpX8Xtav+k9rjn2yPIz5KL8/KN8GpKmlZOVLNs/5XPEjt20ONVppPedvwhmapWl3gS7FjpOIdkCjrz+0W6ZYOBZafLiZt+dhY0uSs8zCWtyfTWrKDrmly2HSMTqFA0U2G7DXo2ocuGLBxBZ6KlfgN8WKZbM/eaVYmURbMtApwSkz6/34dkvExWqewKBWvhi6qB3TWPN5fp1gvh/F50cQlFnA5FIPmkxzTxCNnHMkLcLNiHMNIXCFgKKuMM=
  on:
    tags: true