# This is a basic workflow to help you get started with Actions

name: Publish to PyPI

# Upload only tagged commits
# on:
#   push:
#     tags:
#       - '*'

on:
    push:
    branches: [ main ]
    pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/checkout@master
      - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
      - name: Install dependencies
      run: |
          python -m pip install --upgrade pip

      - name: Build binary wheel and a source tarball
      run: python setup.py sdist
      # Runs a single command using the runners shell
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
